######################################################################
# Automatically generated by qmake (2.01a) ?? 8? 17 20:10:59 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += draglabel.h filelock.hpp musicsimulation.h paintwidget.h widget.h
FORMS += musicsimulation.ui
SOURCES += draglabel.cpp main.cpp musicsimulation.cpp paintwidget.cpp widget.cpp
